apiVersion: apps/v1
kind: Deployment
metadata:
  name: sba-python-deployment
spec:
  selector:
    matchLabels:
      app: sba-python
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: sba-python
    spec:
      containers:
      - name: sba-python-container
        image: kcharette/sba-python:v1
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: sba-python-service
spec:
  type: NodePort
  selector:
    app: sba-python
  ports:
  - protocol: "TCP"
    port: 8090
    targetPort: 8090
    nodePort: 30007
 